import type { Movie } from '../../types/movie'

export const movies: Movie[] = [
  {
    id: 'spider-man-brand-new-day',
    slug: 'spider-man-brand-new-day',
    title: 'Spider-Man: Brand New Day',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 9.2,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWaHpRFpFQk41N1Gz9tAYXtronk1QFa0ecdgMXTTIb4_NzTKfubXWXxnFSQVUqd4GRekf1hh9Kjv1pDtezfAJpX4iusWGoveD42mnIJVVwwR0IINr9HSE_TEQIC1iKhjnTI6QnbLpH0GJv6Q42KUcSUFx1KaOvNeI7JTgwx-i3TpTv5ZGna6gSUTqHA_LI6lNvWzBc8Q72QvTQkKjSGCp1MTI6FcnD-LXJlCKYAID_DVLw_Euu1XBw8g',
    trailerUrl: 'https://www.youtube.com/watch?v=F6QDI4oTYJY',
    heroDescription: 'A new era begins. Peter Parker faces his greatest challenge yet as a mysterious new villain plunges the city into darkness. Experience the visual spectacle in stunning IMAX.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'dune-part-two',
    slug: 'dune-part-two',
    title: 'Dune: Part Two',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 8.9,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAf-MNE_i4UEaWjfbH9XFbN1lyGhVJrN4qJdgEx_jPyLkkzS1RH8-q4nPAkkUPaPFI4-6J6sgRQu5gYmiqg-p6DDotLyAdQhKYbaM7Qqfdsazwj9TrXB0RJBNPD2hQwCz_M_kOYu_ReZ_c-69JXK7Dpu-A4QTJAuLNqaMHMbYLSCNQ03gFsLh-0yV5T-qEpO4lrVEAC-X-sQ7u6mkjuBbaoQT1Gi0k6wf8meHepiEuD5cDhlLkCKbp6Lg',
    trailerUrl: 'https://www.youtube.com/watch?v=n9xhJrPXop4',
    heroDescription: 'The prophecy unfolds as Paul Atreides unites with the Fremen to challenge the empire and destiny itself.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'oppenheimer',
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    genres: ['Biography', 'Drama', 'History'],
    rating: 8.6,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAh6yIMrBRu2NcIgy9lmJnKjxu-H_1lLxELG5g16oCeUZrhhgLsIQtYuZIwAWtguG00wp9Iy9k6Pok43dnnH_6gtsIgOWBcoiRJoo9j8HYm-DWvLrgsdlistYDUro5iQRM8SchvV8MremovVG4dLvqm8XYC1Oh7P1EQ5J75AjFNsG4hW36Z0Gp4KqueP1ykqqhXAXm2sZMjiljYNXiffxJRwGhTf_HWgM7Ul1nFm3-zLMjAV8m4uUkf8g',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    heroDescription: 'A dramatic portrait of the scientist behind the atomic age and the irreversible cost of genius.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'the-batman',
    slug: 'the-batman',
    title: 'The Batman',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.5,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4Og-K02WOZ5LDtX6_Qp8V1wiUKpalyTyeCmhOoPWbNY1z-L-QKkhxAaHfk8Q_RTEjfekpyvAMioAYIbepL57VXl3GxXpVky9QsfpV9BIF05u5vYvrs0I0AVOWzK2PxNGnGUhTzq2m92glSaRI-WMd9lRW-vNC7zrrEHpJlXEbtTIvfvgU08X_LKFdZX8YpFg3q-E3X971AW6ij1Mureh3gXaOwetDnDGqb1s3i5q_dcXTOk_n2BLHbA',
    trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
    heroDescription: 'Gotham is drowning in corruption and fear. One vigilante dives into the shadows to uncover the truth.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
  {
    id: 'interstellar',
    slug: 'interstellar',
    title: 'Interstellar',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 9.0,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAvvefKHPK64eZVgs2ZoBFPemSEIM6bQMWdPVLPWMMrcMCc4EIRf38u0aIaRru03tIT3qiyX-1NQEkOqV7d4v5PKiVoxYt1BE2Kqs9O6oQCXZZTvm46q8O5S6DIUqgxWserNXr4IwiqE91smox7M9UQrkJA1tFN6EF4DwbVInGtpA0BpiFmICyyOmV_6OJ-uRYG4g1aEFmA7a80fsMpJhpne8nMZQhsDTZNeJOtjKL13pQcm01hNyfDIQ',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    heroDescription: 'Humanity pushes beyond the stars in a breathtaking mission to find a second home.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
  {
    id: 'inception',
    slug: 'inception',
    title: 'Inception',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3GIn2tKYCyWCqHPjUL9H7HrYbc7oOvsMTlx4zkriffYV55tCfjjEu0KinlUYN6Sqngqx4feFCPksm2XydtYKtJK7LXtqbJZLbWyhSQukvAz_rDYIqPy1y0hBXs0VyNaTe8jif9Ygw3eQGzxoVIQ9eQ_OAdFHtO-9-v7TPLIdLTPks0rIERC_YCOYUuP_C2JjdBI6DRblGZIn4RtuJEON7LAS8rSK5Yjmb44Mm6C6zYDY3UmHNine6lA',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    heroDescription: 'A thief who steals secrets from dreams must plant an idea that could change everything.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'avatar-the-way-of-water',
    slug: 'avatar-the-way-of-water',
    title: 'Avatar: The Way of Water',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.7,
    posterUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=d9MyW72ELq0',
    heroDescription: 'A new chapter of Pandora unfolds as love, survival, and wonder collide across a living world.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'top-gun-maverick',
    slug: 'top-gun-maverick',
    title: 'Top Gun: Maverick',
    genres: ['Action', 'Drama'],
    rating: 8.4,
    posterUrl: 'https://images.unsplash.com/photo-1549368236-8aa4b72e7f5a?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=qSqVVswa420',
    heroDescription: 'A fearless pilot returns to the edge with a mission that asks more of him than ever before.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'the-dark-knight',
    slug: 'the-dark-knight',
    title: 'The Dark Knight',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 9.1,
    posterUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc98ed?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    heroDescription: 'The city demands courage, truth, and sacrifice from a man who is more than a symbol.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
  {
    id: 'the-matrix-resurrections',
    slug: 'the-matrix-resurrections',
    title: 'The Matrix Resurrections',
    genres: ['Action', 'Sci-Fi'],
    rating: 8.2,
    posterUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=9ix7TUGVYIo',
    heroDescription: 'A familiar world bends into uncertainty as the line between choice and control disappears.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
]

