import type { Movie } from '../../types/movie'

export const movies: Movie[] = [
  {
    id: 'spider-man-brand-new-day',
    slug: 'spider-man-brand-new-day',
    title: 'Spider-Man: Brand New Day',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 9.2,
    posterUrl: '/public/catalogue/spider-man-brand-new-day.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=F6QDI4oTYJY',
    heroDescription: 'A new era begins. Peter Parker faces his greatest challenge yet as a mysterious new villain plunges the city into darkness. Experience the visual spectacle in stunning IMAX.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'dune-part-two',
    slug: 'dune-part-two',
    title: 'Dune: Part Two',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 8.9,
    posterUrl: '/public/catalogue/dune-part-two.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=n9xhJrPXop4',
    heroDescription: 'The prophecy unfolds as Paul Atreides unites with the Fremen to challenge the empire and destiny itself.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'oppenheimer',
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    genres: ['Biography', 'Drama', 'History'],
    rating: 8.6,
    posterUrl: '/public/catalogue/oppenheimer.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    heroDescription: 'A dramatic portrait of the scientist behind the atomic age and the irreversible cost of genius.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
  {
    id: 'the-batman',
    slug: 'the-batman',
    title: 'The Batman',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.5,
    posterUrl: '/public/catalogue/the-batman.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
    heroDescription: 'Gotham is drowning in corruption and fear. One vigilante dives into the shadows to uncover the truth.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
  {
    id: 'interstellar',
    slug: 'interstellar',
    title: 'Interstellar',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 9.0,
    posterUrl: '/public/catalogue/interstellar.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    heroDescription: 'Humanity pushes beyond the stars in a breathtaking mission to find a second home.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
  },
  {
    id: 'inception',
    slug: 'inception',
    title: 'Inception',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
    posterUrl: '/public/catalogue/inception.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    heroDescription: 'A thief who steals secrets from dreams must plant an idea that could change everything.',
    heroTag: 'Now Showing',
    status: 'now-showing',
  },
]

