export const catalogueMovies = [
  {
    id: 'movie-1',
    title: 'Oppenheimer',
    slug: 'oppenheimer',
    posterUrl: '/public/catalogue/oppenheimer.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    heroDescription: 'A dramatic portrait of the scientist behind the atomic age and the irreversible cost of genius.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Biography', 'Drama', 'History'],
    rating: 8.6,
  },
  {
    id: 'movie-2',
    title: 'Interstellar',
    slug: 'interstellar',
    posterUrl: '/public/catalogue/interstellar.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    heroDescription: 'Humanity pushes beyond the stars in a breathtaking mission to find a second home.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 9.0,
  },
  {
    id: 'movie-3',
    title: 'Dune: Part Two',
    slug: 'dune-part-two',
    posterUrl: '/public/catalogue/dune-part-two.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    heroDescription: 'The prophecy unfolds as Paul Atreides unites with the Fremen to challenge the empire and destiny itself.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 8.9,
  },
  {
    id: 'movie-4',
    title: 'Inception',
    slug: 'inception',
    posterUrl: '/public/catalogue/inception.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    heroDescription: 'A thief who steals secrets from dreams must plant an idea that could change everything.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
  },
  {
    id: 'movie-5',
    title: 'The Batman',
    slug: 'the-batman',
    posterUrl: '/public/catalogue/the-batman.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
    heroDescription: 'Gotham is drowning in corruption and fear. One vigilante dives into the shadows to uncover the truth.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.5,
  },
  {
    id: 'movie-6',
    title: 'Spider-Man: Brand New Day',
    slug: 'spider-man-brand-new-day',
    posterUrl: '/public/catalogue/spider-man-brand-new-day.svg',
    trailerUrl: 'https://www.youtube.com/watch?v=F6QDI4oTYJY',
    heroDescription: 'Peter Parker faces a new challenge in a city that never stops moving.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 9.2,
  },
]

export const catalogueRooms = [
  {
    id: 'room-imax',
    name: 'IMAX Hall',
    code: 'IMAX-01',
    capacity: 180,
    type: 'imax',
  },
  {
    id: 'room-premium',
    name: 'Premium Hall',
    code: 'PREMIUM-02',
    capacity: 120,
    type: 'premium',
  },
  {
    id: 'room-screen-3',
    name: 'Screen 3',
    code: 'SCREEN-03',
    capacity: 110,
    type: 'standard',
  },
]

export const catalogueSeats = [
  { id: 'seat-a1', roomId: 'room-imax', label: 'A1', status: 'available' },
  { id: 'seat-a2', roomId: 'room-imax', label: 'A2', status: 'available' },
  { id: 'seat-b1', roomId: 'room-premium', label: 'B1', status: 'available' },
  { id: 'seat-b2', roomId: 'room-premium', label: 'B2', status: 'available' },
  { id: 'seat-c1', roomId: 'room-screen-3', label: 'C1', status: 'available' },
  { id: 'seat-c2', roomId: 'room-screen-3', label: 'C2', status: 'available' },
]

export const catalogueShowtimes = [
  {
    id: 'show-1',
    movieId: 'movie-1',
    roomId: 'room-imax',
    startsAt: '2026-08-08T18:30:00.000Z',
    priceCents: 45000,
  },
  {
    id: 'show-2',
    movieId: 'movie-2',
    roomId: 'room-premium',
    startsAt: '2026-08-08T20:15:00.000Z',
    priceCents: 42000,
  },
  {
    id: 'show-3',
    movieId: 'movie-3',
    roomId: 'room-screen-3',
    startsAt: '2026-08-08T19:00:00.000Z',
    priceCents: 39000,
  },
]

export const cataloguePayload = {
  movies: catalogueMovies,
  rooms: catalogueRooms,
  seats: catalogueSeats,
  showtimes: catalogueShowtimes,
}
