export const catalogueMovies = [
  {
    id: 'movie-1',
    title: 'Oppenheimer',
    slug: 'oppenheimer',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    heroDescription: 'A dramatic portrait of the scientist behind the atomic age and the irreversible cost of genius.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Biography', 'Drama', 'History'],
    rating: 8.6,
  },
  {
    id: 'movie-2',
    title: 'Interstellar',
    slug: 'interstellar',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    heroDescription: 'Humanity pushes beyond the stars in a breathtaking mission to find a second home.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 9.0,
  },
  {
    id: 'movie-3',
    title: 'Dune: Part Two',
    slug: 'dune-part-two',
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    heroDescription: 'The prophecy unfolds as Paul Atreides unites with the Fremen to challenge the empire and destiny itself.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 8.9,
  },
  {
    id: 'movie-4',
    title: 'Inception',
    slug: 'inception',
    posterUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc98ed?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    heroDescription: 'A thief who steals secrets from dreams must plant an idea that could change everything.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
  },
  {
    id: 'movie-5',
    title: 'The Batman',
    slug: 'the-batman',
    posterUrl: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
    heroDescription: 'Gotham is drowning in corruption and fear. One vigilante dives into the shadows to uncover the truth.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.5,
  },
  {
    id: 'movie-6',
    title: 'Avatar: The Way of Water',
    slug: 'avatar-the-way-of-water',
    posterUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=d9MyW72ELq0',
    heroDescription: 'A new chapter of Pandora unfolds as love, survival, and wonder collide across a living world.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.7,
  },
  {
    id: 'movie-7',
    title: 'Top Gun: Maverick',
    slug: 'top-gun-maverick',
    posterUrl: 'https://images.unsplash.com/photo-1549368236-8aa4b72e7f5a?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=qSqVVswa420',
    heroDescription: 'A fearless pilot returns to the edge with a mission that asks more of him than ever before.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Drama'],
    rating: 8.4,
  },
  {
    id: 'movie-8',
    title: 'Spider-Man: Brand New Day',
    slug: 'spider-man-brand-new-day',
    posterUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=2YjK1aWZ3_0',
    heroDescription: 'Peter Parker faces a new challenge in a city that never stops moving.',
    heroTag: 'Now Showing',
    status: 'now-showing',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 9.2,
  },
  {
    id: 'movie-9',
    title: 'The Dark Knight',
    slug: 'the-dark-knight',
    posterUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc98ed?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    heroDescription: 'The city demands courage, truth, and sacrifice from a man who is more than a symbol.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 9.1,
  },
  {
    id: 'movie-10',
    title: 'The Matrix Resurrections',
    slug: 'the-matrix-resurrections',
    posterUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=9ix7TUGVYIo',
    heroDescription: 'A familiar world bends into uncertainty as the line between choice and control disappears.',
    heroTag: 'Coming Soon',
    status: 'coming-soon',
    genres: ['Action', 'Sci-Fi'],
    rating: 8.2,
  },
]

export const catalogueRooms = [
  {
    id: 'room-imax',
    name: 'IMAX Hall',
    code: 'IMAX-01',
    capacity: 180,
    type: 'imax',
  },
  {
    id: 'room-premium',
    name: 'Premium Hall',
    code: 'PREMIUM-02',
    capacity: 120,
    type: 'premium',
  },
  {
    id: 'room-screen-3',
    name: 'Screen 3',
    code: 'SCREEN-03',
    capacity: 110,
    type: 'standard',
  },
]

export const catalogueSeats = [
  { id: 'seat-a1', roomId: 'room-imax', label: 'A1', status: 'available' },
  { id: 'seat-a2', roomId: 'room-imax', label: 'A2', status: 'available' },
  { id: 'seat-b1', roomId: 'room-premium', label: 'B1', status: 'available' },
  { id: 'seat-b2', roomId: 'room-premium', label: 'B2', status: 'available' },
  { id: 'seat-c1', roomId: 'room-screen-3', label: 'C1', status: 'available' },
  { id: 'seat-c2', roomId: 'room-screen-3', label: 'C2', status: 'available' },
]

export const catalogueShowtimes = [
  {
    id: 'show-1',
    movieId: 'movie-1',
    roomId: 'room-imax',
    startsAt: '2026-08-08T18:30:00.000Z',
    priceCents: 45000,
  },
  {
    id: 'show-2',
    movieId: 'movie-2',
    roomId: 'room-premium',
    startsAt: '2026-08-08T20:15:00.000Z',
    priceCents: 42000,
  },
  {
    id: 'show-3',
    movieId: 'movie-3',
    roomId: 'room-screen-3',
    startsAt: '2026-08-08T19:00:00.000Z',
    priceCents: 39000,
  },
]

export const cataloguePayload = {
  movies: catalogueMovies,
  rooms: catalogueRooms,
  seats: catalogueSeats,
  showtimes: catalogueShowtimes,
}
